"""
Utilities for reading rasterized/real image pairs from NavSim JSONL manifests.

The dataset expects:
- A JSONL manifest generated by build_openscene_rap_image_dataset.py or
  build_diverse_sub_dataset.py where each line is {log_stem: [[frame_idx, cam], ...]}.
- A directory of NavSim pickle logs (log_stem.pkl) that contain per-frame camera
  entries with a 'data_path' pointing to the image file location.
- Roots for real sensor blobs and rendered sensor blobs; data_path is joined to
  each root to form full image file paths.

When `load_images=True` and no custom transform is provided, images are loaded
via PIL (RGB) and processed exactly as in RAP bev_feature_build.py:
Normalize -> Scale (0.4x) -> Pad to /32 -> CHW tensor.
"""

from __future__ import annotations

import json
import pickle
from pathlib import Path
from typing import Callable, Dict, Iterable, List, Optional, Tuple

import h5py
from calibration.utils import rap_preprocess_image
from PIL import Image
import numpy as np
import torch
from torch.utils.data import Dataset

ManifestEntry = Tuple[str, int, str]  # (log_id, frame_idx, cam_name)


def load_manifest(manifest_path: Path) -> List[ManifestEntry]:
    """
    Load every (log_id, frame_idx, cam_name) triple from a JSONL manifest.

    The manifest format mirrors the outputs of build_openscene_rap_image_dataset.py
    and build_diverse_sub_dataset.py.
    """
    entries: List[ManifestEntry] = []
    with open(manifest_path, "r", encoding="utf-8") as f:
        for line_no, raw in enumerate(f, start=1):
            line = raw.strip()
            if not line:
                continue
            payload = json.loads(line)
            if not payload:
                continue
            if len(payload) != 1:
                raise ValueError(
                    f"Line {line_no} in {manifest_path} should contain one log mapping, "
                    f"found keys {list(payload)}"
                )
            log_id, pairs = next(iter(payload.items()))
            for frame_idx, cam_name in pairs:
                if frame_idx is None:
                    raise ValueError(f"Missing frame_idx for {log_id}:{cam_name} on line {line_no}")
                entries.append((str(log_id), int(frame_idx), str(cam_name)))
    return entries


def load_image_bgr(path: Path) -> np.ndarray:
    """
    Load an image via PIL to match RAP's original pipeline (RGB uint8 array).
    """
    try:
        return np.array(Image.open(path))
    except FileNotFoundError:
        raise
    except Exception as exc:
        raise FileNotFoundError(f"Failed to read image: {path}") from exc


class RasterRealPairDataset(Dataset):
    """
    Torch dataset that resolves rendered and real image paths for NavSim pairs.

    By default it returns file paths and metadata only; set load_images=True to also
    decode images. If no transform is provided, RAP BEV-style preprocessing
    (normalize -> scale -> pad, matching bev_feature_build.py) is applied.
    """

    def __init__(
        self,
        manifest_path: Path,
        log_root: Path,
        sensor_root: Path,
        rendered_root: Path,
        *,
        load_images: bool = False,
        transform: Optional[Callable[[np.ndarray], object]] = None,
        loader: Callable[[Path], np.ndarray] = load_image_bgr,
        log_suffix: str = ".pkl",
    ) -> None:
        self.entries = load_manifest(manifest_path)
        self.log_root = Path(log_root)
        self.sensor_root = Path(sensor_root)
        self.rendered_root = Path(rendered_root)
        self.load_images = load_images
        if self.load_images and transform is None:
            # Default to RAP BEV-style preprocessing when loading images.
            self.transform = rap_preprocess_image
        else:
            self.transform = transform
        self.loader = loader
        self.log_suffix = log_suffix

        self._log_cache: Dict[str, Dict[Tuple[int, str], str]] = {}

    def __len__(self) -> int:  # pragma: no cover - trivial
        return len(self.entries)

    def __getitem__(self, idx: int):
        while idx < len(self.entries):
            log_id, frame_idx, cam_name = self.entries[idx]
            data_path = self._lookup_data_path(log_id, frame_idx, cam_name)
            if data_path is None:
                idx += 1
                continue

            real_path = self.sensor_root / data_path
            rendered_path = self.rendered_root / data_path

            if not real_path.exists() or not rendered_path.exists():
                idx += 1
                continue

            sample = {
                "log_id": log_id,
                "frame_idx": frame_idx,
                "cam_name": cam_name,
                "real_path": real_path,
                "rendered_path": rendered_path,
            }
            if self.load_images:
                try:
                    rendered_img = self.loader(rendered_path)[20:-20]
                except Exception:
                    rendered_img = np.zeros((1080, 1920, 3), dtype=np.float32)

                try:
                    real_img = self.loader(real_path)
                    real_valid = True
                except Exception:
                    real_img = np.zeros_like(rendered_img)
                    real_valid = False

                assert real_img.shape == rendered_img.shape, (
                    f"Loaded real/rendered shapes differ: {real_img.shape} vs {rendered_img.shape}"
                )

                if self.transform:
                    real_img = self.transform(real_img)
                    rendered_img = self.transform(rendered_img)

                assert real_img.shape == rendered_img.shape, (
                    f"Processed real/rendered shapes differ: {real_img.shape} vs {rendered_img.shape}"
                )
                sample["real_image"] = real_img
                sample["rendered_image"] = rendered_img
                sample["real_valid"] = real_valid

            return sample

        raise IndexError(f"No valid entries found starting at index {idx}")

    def _lookup_data_path(self, log_id: str, frame_idx: int, cam_name: str) -> Optional[str]:
        """Find the data_path for a frame/cam tuple from the cached log pickle."""
        if log_id not in self._log_cache:
            self._log_cache[log_id] = self._load_log_index(log_id)
        index = self._log_cache.get(log_id) or {}
        return index.get((frame_idx, cam_name))

    def _load_log_index(self, log_id: str) -> Dict[Tuple[int, str], str]:
        """
        Load a NavSim pickle log and index it by (frame_idx, cam_name) -> data_path.

        The structure mirrors build_openscene_rap_image_dataset.process_log_file.
        """
        log_path = self.log_root / "trainval" / f"{log_id}{self.log_suffix}"
        if not log_path.exists():
            alt_log_path = self.log_root / "test" / f"{log_id}{self.log_suffix}"
            if alt_log_path.exists():
                log_path = alt_log_path
            else:
                return {}

        try:
            with open(log_path, "rb") as f:
                frames = pickle.load(f)
        except Exception:
            return {}

        index: Dict[Tuple[int, str], str] = {}
        for frame in frames:
            frame_idx = frame.get("frame_idx")
            cams = frame.get("cams") or {}
            for cam_name, cam_entry in cams.items():
                data_path = cam_entry.get("data_path")
                if frame_idx is None or data_path is None:
                    continue
                index[(int(frame_idx), str(cam_name))] = str(data_path)
        return index


# --- BEV-style preprocessing helpers -----------------------------------------------------

def make_bev_transform(
    *,
    scale: Optional[float] = 0.4,
    pad_divisor: int = 32,
    to_rgb: bool = False,
):
    """
    Compatibility wrapper returning RAP's preprocessing function.
    """
    if scale != 0.4 or pad_divisor != 32 or to_rgb:
        raise ValueError("RAP preprocessing is fixed; override unsupported.")
    return rap_preprocess_image


def iter_pairs(
    manifest_path: Path,
    log_root: Path,
    sensor_root: Path,
    rendered_root: Path,
) -> Iterable[Dict[str, object]]:
    """
    Lightweight iterator over manifest entries that yields resolved file paths.

    This avoids bringing in torch.utils.data when only path resolution is needed.
    """
    dataset = RasterRealPairDataset(
        manifest_path=manifest_path,
        log_root=log_root,
        sensor_root=sensor_root,
        rendered_root=rendered_root,
        load_images=False,
    )
    for item in dataset:
        yield item


def feature_cache_file(cache_root: Path, log_id: str) -> Path:
    """
    Build a cache file path for precomputed features grouped by log.
    """
    return Path(cache_root) / f"{log_id}.h5"


def feature_cache_path(
    cache_root: Path, log_id: str, frame_idx: int, cam_name: str, kind: str
) -> Path:
    """
    Backwards-compatible wrapper returning the HDF5 cache file path.
    """
    return feature_cache_file(cache_root, log_id)


def feature_cache_group(frame_idx: int, cam_name: str, kind: str) -> str:
    """
    Build a group key inside an HDF5 cache file.
    """
    return f"{int(frame_idx):06d}/{cam_name}/{kind}"


class CachedRasterRealPairDataset(RasterRealPairDataset):
    """
    Dataset that serves cached backbone features instead of recomputing them.
    """

    def __init__(
        self,
        *args,
        cache_root: Path,
        load_features: bool = True,
        map_location: str = "cpu",
        **kwargs,
    ) -> None:
        super().__init__(*args, **kwargs)
        self.cache_root = Path(cache_root)
        self.load_features = load_features
        self.map_location = map_location
        self._open_files: Dict[str, h5py.File] = {}

    def __getitem__(self, idx: int):
        sample = super().__getitem__(idx)
        if not self.load_features:
            return sample

        log_id = sample["log_id"]
        frame_idx = sample["frame_idx"]
        cam_name = sample["cam_name"]

        cache_path = feature_cache_file(self.cache_root, log_id)
        real_group = feature_cache_group(frame_idx, cam_name, "real")
        rendered_group = feature_cache_group(frame_idx, cam_name, "rendered")

        if not cache_path.exists():
            raise FileNotFoundError(f"Cached feature file not found: {cache_path}")

        def _get_file() -> h5py.File:
            f = self._open_files.get(log_id)
            if f is None or not f.id or not f.id.valid:
                f = h5py.File(cache_path, "r")
                self._open_files[log_id] = f
            return f

        def _load_group(group_name: str):
            f = _get_file()
            if group_name not in f:
                raise FileNotFoundError(f"Cached feature group not found: {cache_path}:{group_name}")
            grp = f[group_name]
            feats = [torch.as_tensor(grp[k][()], device=self.map_location) for k in sorted(grp.keys())]
            return feats[0] if len(feats) == 1 else tuple(feats)

        sample["real_feature_path"] = cache_path
        sample["rendered_feature_path"] = cache_path
        sample["real_feature"] = _load_group(real_group)
        sample["rendered_feature"] = _load_group(rendered_group)
        return sample

    def __del__(self):
        for f in self._open_files.values():
            try:
                f.close()
            except Exception:
                pass


# Backwards-compatible alias.
CachedDataloader = CachedRasterRealPairDataset
