#!/usr/bin/env python3
"""
PyTorch Lightning training scaffold for TransFuser BEV flow matching.

Key behaviors:
- Loads MetaDrive/NavSim token pairs from separate train/val JSONL files.
- Loads precomputed BEV embeddings from H5 cache files.
- Runs a FlowMatching model to learn BEV-to-BEV transformations.
- Source domain: always MetaDrive
- Target domain: navsim or navsim_no_lidar (configurable)

Assumptions:
- BEV cache must be precomputed using precompute_transfuser_bev_cache.py.
- Token pairs generated by build_transfuser_bev_pairs.py.
- TransFuser BEV shape: (512, 8, 8)
"""

from __future__ import annotations

import argparse
import gc
import json
import random
from copy import deepcopy
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Set

import h5py
import torch
import pytorch_lightning as pl
import wandb
from pytorch_lightning.callbacks import LearningRateMonitor, ModelCheckpoint
from pytorch_lightning.loggers import WandbLogger
from torch.optim.lr_scheduler import CosineAnnealingLR, LambdaLR
from torch.utils.data import DataLoader, Dataset

from flow_matching_model import FlowMatchingModel


# TransFuser BEV dimensions
TRANSFUSER_BEV_CHANNELS = 512
TRANSFUSER_BEV_HW = 8


@dataclass
class TokenEntry:
    """Entry from transfuser_bev_pairs.jsonl."""

    token: str
    log_name: str
    navsim_h5: str
    navsim_no_lidar_h5: str
    metadrive_h5: str


def replace_path_prefix(path: str, old_prefix: str, new_prefix: str) -> str:
    """Replace path prefix if it matches."""
    if path.startswith(old_prefix):
        return new_prefix + path[len(old_prefix):]
    return path


def load_token_entries(
    path: Path,
    old_path_prefix: Optional[str] = None,
    new_path_prefix: Optional[str] = None,
) -> List[TokenEntry]:
    """
    Load token entries from JSONL file.

    Args:
        path: Path to JSONL file
        old_path_prefix: If provided, replace this prefix in all H5 paths
        new_path_prefix: Replacement prefix (required if old_path_prefix is set)
    """
    entries: List[TokenEntry] = []

    # Validate prefix args
    if (old_path_prefix is None) != (new_path_prefix is None):
        raise ValueError(
            "Both --old-path-prefix and --new-path-prefix must be provided together"
        )

    do_replace = old_path_prefix is not None and new_path_prefix is not None

    with path.open("r", encoding="utf-8") as f:
        for line_no, raw in enumerate(f, start=1):
            line = raw.strip()
            if not line:
                continue
            payload = json.loads(line)
            try:
                navsim_h5 = str(payload["navsim_h5"])
                navsim_no_lidar_h5 = str(payload["navsim_no_lidar_h5"])
                metadrive_h5 = str(payload["metadrive_h5"])

                # Apply path prefix replacement if configured
                if do_replace:
                    navsim_h5 = replace_path_prefix(
                        navsim_h5, old_path_prefix, new_path_prefix
                    )
                    navsim_no_lidar_h5 = replace_path_prefix(
                        navsim_no_lidar_h5, old_path_prefix, new_path_prefix
                    )
                    metadrive_h5 = replace_path_prefix(
                        metadrive_h5, old_path_prefix, new_path_prefix
                    )

                entries.append(
                    TokenEntry(
                        token=str(payload["token"]),
                        log_name=str(payload["log_name"]),
                        navsim_h5=navsim_h5,
                        navsim_no_lidar_h5=navsim_no_lidar_h5,
                        metadrive_h5=metadrive_h5,
                    )
                )
            except KeyError as exc:
                raise ValueError(f"Missing field {exc} on line {line_no}") from exc

    if do_replace and entries:
        print(f"Replaced path prefix: '{old_path_prefix}' -> '{new_path_prefix}'")
        print(f"Example path: {entries[0].navsim_h5}")

    return entries


def set_seed(seed: int) -> None:
    random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def build_optimizer(params, name: str, lr: float, weight_decay: float = 0.0):
    name = name.lower()
    if name == "adam":
        return torch.optim.Adam(params, lr=lr, weight_decay=weight_decay)
    if name == "adamw":
        return torch.optim.AdamW(params, lr=lr, weight_decay=weight_decay)
    raise ValueError(f"Unsupported optimizer {name}")


def build_lr_scheduler(
    optimizer, name: str, *, warmup_steps: int = -1, t_max: int = 100
):
    name = name.lower()
    if name == "none":
        return None
    if name == "customized":

        def fn(step: int):
            if warmup_steps > 0:
                return min(step / warmup_steps, 1.0)
            return 1.0

        return LambdaLR(optimizer, fn)
    if name == "cosine":
        return CosineAnnealingLR(optimizer, T_max=t_max)
    raise ValueError(f"Unsupported lr scheduler {name}")


def collect_h5_paths(entries: List[TokenEntry], target_domain: str) -> Set[str]:
    """Collect unique H5 file paths from entries."""
    paths: Set[str] = set()
    for entry in entries:
        paths.add(entry.metadrive_h5)
        if target_domain == "navsim":
            paths.add(entry.navsim_h5)
        else:
            paths.add(entry.navsim_no_lidar_h5)
    return paths


class H5CacheManager:
    """Context manager for efficient H5 file access."""

    def __init__(self, h5_paths: Set[str]):
        self.h5_paths = h5_paths
        self.handles: Dict[str, h5py.File] = {}

    def __enter__(self) -> Dict[str, h5py.File]:
        for path in self.h5_paths:
            if Path(path).exists():
                self.handles[path] = h5py.File(path, "r")
        return self.handles

    def __exit__(self, *args):
        for f in self.handles.values():
            f.close()
        self.handles.clear()


class TransFuserPairDataset(Dataset):
    """Loads BEV pairs from H5 cache files.

    Note: H5 files are opened lazily per-worker to avoid issues with
    multiprocessing. Each worker maintains its own file handles.
    """

    def __init__(
        self,
        entries: List[TokenEntry],
        h5_paths: Set[str],
        target_domain: str = "navsim",
    ):
        self.entries = entries
        self.h5_paths = h5_paths
        self.target_domain = target_domain
        # H5 cache opened lazily per-worker
        self._h5_cache: Optional[Dict[str, h5py.File]] = None
        self._worker_id: Optional[int] = None

    def _get_h5_cache(self) -> Dict[str, h5py.File]:
        """Get or create H5 cache for current worker."""
        worker_info = torch.utils.data.get_worker_info()
        current_worker_id = worker_info.id if worker_info else -1

        # Re-open files if worker changed or first access
        if self._h5_cache is None or self._worker_id != current_worker_id:
            self._close_h5_cache()
            self._h5_cache = {}
            for path in self.h5_paths:
                if Path(path).exists():
                    self._h5_cache[path] = h5py.File(path, "r")
            self._worker_id = current_worker_id

        return self._h5_cache

    def _close_h5_cache(self):
        """Close any open H5 files."""
        if self._h5_cache is not None:
            for f in self._h5_cache.values():
                try:
                    f.close()
                except Exception:
                    pass
            self._h5_cache = None

    def __del__(self):
        """Cleanup H5 files on deletion."""
        self._close_h5_cache()

    def __len__(self) -> int:
        return len(self.entries)

    def __getitem__(self, idx: int):
        entry = self.entries[idx]
        h5_cache = self._get_h5_cache()

        # Get target H5 path based on domain
        if self.target_domain == "navsim":
            target_h5_path = entry.navsim_h5
        else:
            target_h5_path = entry.navsim_no_lidar_h5

        # Check if H5 files are available
        if entry.metadrive_h5 not in h5_cache:
            return None
        if target_h5_path not in h5_cache:
            return None

        try:
            metadrive_h5 = h5_cache[entry.metadrive_h5]
            target_h5 = h5_cache[target_h5_path]

            # Check if token exists in both files
            if entry.token not in metadrive_h5:
                return None
            if entry.token not in target_h5:
                return None

            # Load BEV features
            metadrive_bev = torch.from_numpy(metadrive_h5[entry.token][:]).float()
            target_bev = torch.from_numpy(target_h5[entry.token][:]).float()

            # Return only tensors, not entries (Fix #3: avoid IPC overhead)
            return metadrive_bev, target_bev

        except Exception:
            return None


def collate_fn(batch: List):
    """Collate function that filters None entries.

    Fix #3: Only return tensors, not TokenEntry objects to avoid
    unnecessary object creation and IPC serialization overhead.
    """
    batch = [b for b in batch if b is not None]
    if not batch:
        return None
    metadrive_bevs, target_bevs = zip(*batch)
    metadrive_batch = torch.stack(metadrive_bevs, dim=0)
    target_batch = torch.stack(target_bevs, dim=0)
    return metadrive_batch, target_batch


class FlowMatchingLit(pl.LightningModule):
    """PyTorch Lightning module for TransFuser BEV flow matching."""

    def __init__(
        self,
        lr: float = 1e-4,
        optimizer_name: str = "adamw",
        weight_decay: float = 0.01,
        lr_scheduler_name: str = "customized",
        warmup_steps: int = 500,
        lr_t_max: int = 1000,
        ema_decay: float = 0.9999,
        dit_variant: str = "DiT-S/2",
    ) -> None:
        super().__init__()
        self.save_hyperparameters()
        self.lr = lr
        self.optimizer_name = optimizer_name
        self.weight_decay = weight_decay
        self.lr_scheduler_name = lr_scheduler_name
        self.warmup_steps = warmup_steps
        self.lr_t_max = lr_t_max
        self.ema_decay = ema_decay

        # Flow model configured for TransFuser BEV dimensions
        self.flow_model = FlowMatchingModel(
            default_bev_hw=(TRANSFUSER_BEV_HW, TRANSFUSER_BEV_HW),
            bev_channels=TRANSFUSER_BEV_CHANNELS,
            dit_variant=dit_variant,
        )

        # EMA model
        self.ema_flow_model = deepcopy(self.flow_model)
        for p in self.ema_flow_model.parameters():
            p.requires_grad_(False)

    def on_train_epoch_end(self):
        """Fix #4: Periodic garbage collection during training."""
        gc.collect()
        torch.cuda.empty_cache()

    def on_validation_epoch_end(self):
        gc.collect()
        torch.cuda.empty_cache()

    def configure_optimizers(self):
        optimizer = build_optimizer(
            self.flow_model.parameters(),
            name=self.optimizer_name,
            lr=self.lr,
            weight_decay=self.weight_decay,
        )
        scheduler = build_lr_scheduler(
            optimizer,
            name=self.lr_scheduler_name,
            warmup_steps=self.warmup_steps,
            t_max=self.lr_t_max,
        )
        if scheduler is None:
            return optimizer
        return {
            "optimizer": optimizer,
            "lr_scheduler": {
                "scheduler": scheduler,
                "interval": "step",
            },
        }

    @torch.no_grad()
    def _ema_update(self):
        if self.ema_flow_model is None:
            return
        ema_params = dict(self.ema_flow_model.named_parameters())
        for name, param in self.flow_model.named_parameters():
            ema_param = ema_params[name]
            ema_param.data.mul_(self.ema_decay).add_(
                (1 - self.ema_decay) * param.data
            )

    def _compute_cosine_similarity(
        self,
        src_bchw: torch.Tensor,
        tgt_bchw: torch.Tensor,
    ) -> dict:
        """
        Compute cosine similarity between source and target BEV features.

        Args:
            src_bchw: Source BEV (B, C, H, W) - MetaDrive features
            tgt_bchw: Target BEV (B, C, H, W) - NavSim features

        Returns:
            Dict with cosine similarity metrics:
            - mean: Average cosine similarity across all positions and batch
            - per_position_mean: (H*W,) mean cosine sim for each spatial position
        """
        B, C, H, W = src_bchw.shape

        # Reshape to (B, C, H*W) then transpose to (B, H*W, C)
        src_flat = src_bchw.flatten(2).transpose(1, 2)  # (B, H*W, C)
        tgt_flat = tgt_bchw.flatten(2).transpose(1, 2)  # (B, H*W, C)

        # Normalize along feature dimension
        src_norm = torch.nn.functional.normalize(src_flat, p=2, dim=-1)
        tgt_norm = torch.nn.functional.normalize(tgt_flat, p=2, dim=-1)

        # Cosine similarity per position: (B, H*W)
        cos_sim = (src_norm * tgt_norm).sum(dim=-1)

        # Mean across batch for each position: (H*W,)
        per_position_mean = cos_sim.mean(dim=0)

        # Overall mean
        mean_cos_sim = cos_sim.mean()

        return {
            "mean": mean_cos_sim,
            "per_position_mean": per_position_mean,
        }

    def _flow_step(
        self,
        src_bev: torch.Tensor,
        tgt_bev: torch.Tensor,
        stage: str,
    ):
        """Shared flow-matching computation for train/val.

        Fix #3: Removed entries parameter as it was unused and caused
        unnecessary memory overhead from IPC serialization.
        """
        # Reshape to (B, C, H, W) if needed
        src_bchw = self.flow_model.reshape_bev(src_bev)
        tgt_bchw = self.flow_model.reshape_bev(tgt_bev)

        # Sample timesteps
        t = torch.rand(src_bchw.shape[0], device=self.device)

        # Interpolate and compute target velocity
        x_t = self.flow_model.psi(t, noise=src_bchw, x1=tgt_bchw)
        target_velocity = self.flow_model.dt_psi(t, noise=src_bchw, x1=tgt_bchw)

        # Predict velocity
        v_pred = self.flow_model(x_t, t)

        # MSE loss
        loss = (v_pred - target_velocity).pow(2).flatten(1).mean()

        self.log(
            f"{stage}/loss",
            loss,
            prog_bar=True,
            on_step=(stage == "train"),
            on_epoch=True,
            sync_dist=True,
        )

        return loss

    def optimizer_step(self, *args, **kwargs):
        super().optimizer_step(*args, **kwargs)
        self._ema_update()

    def _run_stage(self, batch, stage: str):
        if batch is None:
            return torch.zeros((), device=self.device)
        src_bev, tgt_bev = batch
        src_bev = src_bev.to(self.device)
        tgt_bev = tgt_bev.to(self.device)
        return self._flow_step(src_bev, tgt_bev, stage=stage)

    def training_step(self, batch, batch_idx: int):
        return self._run_stage(batch, stage="train")

    def validation_step(self, batch, batch_idx: int):
        return self._run_stage(batch, stage="val")

    def test_step(self, batch, batch_idx: int):
        if batch is None:
            return
        src_bev, tgt_bev = batch
        src_bev = src_bev.to(self.device)
        tgt_bev = tgt_bev.to(self.device)

        # Sample from flow model
        sampler_model = (
            self.ema_flow_model if self.ema_flow_model is not None else self.flow_model
        )
        gen_bev = sampler_model.sample(src_bev)

        # Compute reconstruction loss
        gen_bchw = self.flow_model.reshape_bev(gen_bev)
        tgt_bchw = self.flow_model.reshape_bev(tgt_bev)
        loss = (gen_bchw - tgt_bchw).pow(2).flatten(1).mean()

        self.log(
            "test/loss",
            loss.detach(),
            prog_bar=True,
            on_step=False,
            on_epoch=True,
            sync_dist=True,
        )

        # Compute cosine similarity between generated and target BEV
        cos_sim = self._compute_cosine_similarity(gen_bchw, tgt_bchw)

        self.log(
            "test/cosine_sim_mean",
            cos_sim["mean"],
            prog_bar=True,
            on_step=False,
            on_epoch=True,
            sync_dist=True,
        )

        per_pos = cos_sim["per_position_mean"]
        self.log(
            "test/cosine_sim_min",
            per_pos.min(),
            on_step=False,
            on_epoch=True,
            sync_dist=True,
        )
        self.log(
            "test/cosine_sim_max",
            per_pos.max(),
            on_step=False,
            on_epoch=True,
            sync_dist=True,
        )


class PairDataModule(pl.LightningDataModule):
    """Data module for TransFuser BEV pairs.

    Fix #1: H5 files are now opened lazily per-worker in the Dataset
    to avoid issues with multiprocessing and h5py file handles.

    Fix #2: persistent_workers disabled to prevent memory accumulation.
    """

    def __init__(
        self,
        train_pairs_path: Path,
        val_pairs_path: Path,
        target_domain: str = "navsim",
        batch_size: int = 32,
        num_workers: int = 4,
        max_samples: Optional[int] = None,
        old_path_prefix: Optional[str] = None,
        new_path_prefix: Optional[str] = None,
    ) -> None:
        super().__init__()
        self.train_pairs_path = train_pairs_path
        self.val_pairs_path = val_pairs_path
        self.target_domain = target_domain
        self.batch_size = batch_size
        self.num_workers = num_workers
        self.max_samples = max_samples
        self.old_path_prefix = old_path_prefix
        self.new_path_prefix = new_path_prefix

        self.train_entries: List[TokenEntry] = []
        self.val_entries: List[TokenEntry] = []
        self.h5_paths: Set[str] = set()

    def setup(self, stage: Optional[str] = None) -> None:
        # Load entries with optional path prefix replacement
        self.train_entries = load_token_entries(
            self.train_pairs_path,
            old_path_prefix=self.old_path_prefix,
            new_path_prefix=self.new_path_prefix,
        )
        self.val_entries = load_token_entries(
            self.val_pairs_path,
            old_path_prefix=self.old_path_prefix,
            new_path_prefix=self.new_path_prefix,
        )

        if self.max_samples is not None:
            self.train_entries = self.train_entries[: self.max_samples]

        # Collect all H5 paths (files opened lazily per-worker)
        self.h5_paths = collect_h5_paths(
            self.train_entries + self.val_entries, self.target_domain
        )

        print(f"Loaded {len(self.train_entries)} train entries")
        print(f"Loaded {len(self.val_entries)} val entries")
        print(f"Found {len(self.h5_paths)} H5 cache files (opened lazily per-worker)")

    def teardown(self, stage: Optional[str] = None) -> None:
        # H5 files are managed by Dataset instances, nothing to clean up here
        pass

    def train_dataloader(self):
        return DataLoader(
            TransFuserPairDataset(
                self.train_entries,
                h5_paths=self.h5_paths,
                target_domain=self.target_domain,
            ),
            batch_size=self.batch_size,
            shuffle=True,
            num_workers=self.num_workers,
            collate_fn=collate_fn,
            pin_memory=True,
            persistent_workers=False,  # Fix #2: Disable to prevent memory accumulation
        )

    def val_dataloader(self):
        return DataLoader(
            TransFuserPairDataset(
                self.val_entries,
                h5_paths=self.h5_paths,
                target_domain=self.target_domain,
            ),
            batch_size=self.batch_size,
            shuffle=False,
            num_workers=self.num_workers,
            collate_fn=collate_fn,
            pin_memory=True,
            persistent_workers=False,  # Fix #2: Disable to prevent memory accumulation
        )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Lightning training for TransFuser BEV flow matching."
    )
    parser.add_argument(
        "--train-pairs",
        type=Path,
        required=True,
        help="Training pairs JSONL from build_transfuser_bev_pairs.py.",
    )
    parser.add_argument(
        "--val-pairs",
        type=Path,
        required=True,
        help="Validation pairs JSONL from build_transfuser_bev_pairs.py.",
    )
    parser.add_argument(
        "--target-domain",
        type=str,
        default="navsim",
        choices=["navsim", "navsim_no_lidar"],
        help="Target domain for flow matching (default: navsim).",
    )
    parser.add_argument(
        "--old-path-prefix",
        type=str,
        default=None,
        help="Original path prefix to replace in H5 paths from JSONL.",
    )
    parser.add_argument(
        "--new-path-prefix",
        type=str,
        default=None,
        help="New path prefix to use (must be provided with --old-path-prefix).",
    )
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--num-workers", type=int, default=4)
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument(
        "--optimizer",
        type=str,
        default="adamw",
        choices=["adam", "adamw"],
        help="Optimizer type.",
    )
    parser.add_argument("--weight-decay", type=float, default=0.01)
    parser.add_argument(
        "--lr-scheduler",
        type=str,
        default="customized",
        choices=["none", "customized", "cosine"],
    )
    parser.add_argument(
        "--warmup-steps",
        type=int,
        default=500,
        help="Warmup steps for customized scheduler.",
    )
    parser.add_argument(
        "--lr-t-max", type=int, default=1000, help="T_max for cosine scheduler."
    )
    parser.add_argument("--ema-decay", type=float, default=0.9999)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--accelerator",
        type=str,
        default="gpu" if torch.cuda.is_available() else "cpu",
    )
    parser.add_argument(
        "--devices", default="auto", help="Lightning devices arg (e.g., 1, 2, 'auto')."
    )
    parser.add_argument(
        "--strategy",
        type=str,
        default="ddp",
        help="Lightning strategy (e.g., ddp, auto).",
    )
    parser.add_argument(
        "--ckpt-dir",
        type=Path,
        required=True,
        help="Directory to save checkpoints.",
    )
    parser.add_argument(
        "--resume-from",
        type=Path,
        default=None,
        help="Resume from checkpoint path.",
    )
    parser.add_argument(
        "--wandb", action="store_true", help="Enable Weights & Biases logging."
    )
    parser.add_argument(
        "--wandb-project",
        type=str,
        default="TransFuserBevFlow",
        help="W&B project name.",
    )
    parser.add_argument(
        "--model-name",
        type=str,
        default="transfuser",
        help="Model name for wandb run naming (default: transfuser).",
    )
    parser.add_argument(
        "--wandb-run-name",
        type=str,
        default=None,
        help="W&B run name.",
    )
    parser.add_argument(
        "--dit-variant",
        type=str,
        default="DiT-S/2",
        help="DiT architecture variant.",
    )
    parser.add_argument(
        "--max-samples",
        type=int,
        default=None,
        help="Optional cap on number of training samples.",
    )
    parser.add_argument(
        "--save-every-n-epochs",
        type=int,
        default=1,
        help="Save checkpoint every N epochs.",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    set_seed(args.seed)
    pl.seed_everything(args.seed, workers=True)

    torch.set_float32_matmul_precision("high")

    # Validate paths
    if not args.train_pairs.exists():
        raise SystemExit(f"Train pairs file not found: {args.train_pairs}")
    if not args.val_pairs.exists():
        raise SystemExit(f"Val pairs file not found: {args.val_pairs}")

    datamodule = PairDataModule(
        train_pairs_path=args.train_pairs,
        val_pairs_path=args.val_pairs,
        target_domain=args.target_domain,
        batch_size=args.batch_size,
        num_workers=args.num_workers,
        max_samples=args.max_samples,
        old_path_prefix=args.old_path_prefix,
        new_path_prefix=args.new_path_prefix,
    )

    lit_model = FlowMatchingLit(
        lr=args.lr,
        optimizer_name=args.optimizer,
        weight_decay=args.weight_decay,
        lr_scheduler_name=args.lr_scheduler,
        warmup_steps=args.warmup_steps,
        lr_t_max=args.lr_t_max,
        ema_decay=args.ema_decay,
        dit_variant=args.dit_variant,
    )

    # Build run name first (needed for ckpt_dir)
    if args.wandb_run_name is None:
        args.wandb_run_name = f"{args.model_name}-bevflow-{args.dit_variant}-{args.target_domain}"

    # Include run name in checkpoint directory
    ckpt_dir = args.ckpt_dir / args.wandb_run_name
    ckpt_dir.mkdir(parents=True, exist_ok=True)

    checkpoint_cb = ModelCheckpoint(
        dirpath=str(ckpt_dir),
        filename="{epoch}-{step}",
        save_top_k=-1,
        every_n_epochs=args.save_every_n_epochs,
        save_weights_only=False,
    )

    lr_monitor = LearningRateMonitor(logging_interval="step")

    logger = None
    if args.wandb:
        wandb.login(key="caad08df59bfd0cb22f3613849ad66faeb65d4b0")
        logger = WandbLogger(
            project=args.wandb_project,
            name=args.wandb_run_name,
            save_dir=str(ckpt_dir),
            config=vars(args),
        )

    trainer = pl.Trainer(
        max_epochs=args.epochs,
        accelerator=args.accelerator,
        devices=args.devices,
        strategy=args.strategy,
        precision=32,
        logger=logger,
        enable_checkpointing=True,
        callbacks=[checkpoint_cb, lr_monitor],
        log_every_n_steps=10,
        enable_progress_bar=True,
    )

    trainer.fit(
        lit_model,
        datamodule=datamodule,
        ckpt_path=str(args.resume_from) if args.resume_from else None,
    )


if __name__ == "__main__":
    main()
