#!/usr/bin/env python3
"""
PyTorch Lightning training scaffold for UniAD BEV flow matching (single-node multi-GPU).

Key behaviors:
- Loads MetaDrive/Bench2Drive frame pairs and splits using a provided val list;
  everything else is treated as train.
- Loads precomputed BEV embeddings from cache (no on-the-fly BEV extraction).
- Runs a FlowMatching model to learn BEV-to-BEV transformations.
- Optional visualization during test (detections + map/occ overlays) on global rank 0.

Assumptions:
- Uses high precision (no AMP).
- BEV cache must be precomputed using precompute_temporal_bev_cache.py.
- Frame pairs generated by build_bench2drive_metadrive_frame_pairs.py.
- UniAD model loaded only for test visualization.
"""

from __future__ import annotations

import argparse
import json
import random
from copy import deepcopy
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Tuple

import gc
import wandb
import torch
import pytorch_lightning as pl
from torch.utils.data import DataLoader, Dataset
from pytorch_lightning.callbacks import ModelCheckpoint
from pytorch_lightning.loggers import WandbLogger
from torch.optim.lr_scheduler import LambdaLR, CosineAnnealingLR

# Local imports
from flow_matching_model import FlowMatchingModel
from train_uniad_bev import (  # type: ignore
    load_model_and_pipeline,
    visualize_bev,
    run_heads_from_bev,
)


@dataclass
class FrameBundle:
    """Minimal frame bundle for cache lookup - only needs scenario and frame."""
    scenario: str
    frame: str


def load_frame_bundles(path: Path) -> List[FrameBundle]:
    """Load frame bundles from JSONL, extracting only scenario and frame for cache lookup."""
    bundles: List[FrameBundle] = []
    with path.open("r", encoding="utf-8") as f:
        for line_no, raw in enumerate(f, start=1):
            line = raw.strip()
            if not line:
                continue
            payload = json.loads(line)
            try:
                bundles.append(
                    FrameBundle(
                        scenario=str(payload["scenario"]),
                        frame=str(payload["frame"]),
                    )
                )
            except KeyError as exc:
                raise ValueError(f"Missing field {exc} on line {line_no}") from exc
    return bundles


def set_seed(seed: int) -> None:
    random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def build_optimizer(params, name: str, lr: float, weight_decay: float = 0.0):
    name = name.lower()
    if name == "adam":
        return torch.optim.Adam(params, lr=lr, weight_decay=weight_decay)
    if name == "adamw":
        return torch.optim.AdamW(params, lr=lr, weight_decay=weight_decay)
    raise ValueError(f"Unsupported optimizer {name}")


def build_lr_scheduler(optimizer, name: str, *, warmup_steps: int = -1, t_max: int = 100):
    name = name.lower()
    if name == "none":
        return None
    if name == "customized":
        def fn(step: int):
            if warmup_steps > 0:
                return min(step / warmup_steps, 1.0)
            return 1.0
        return LambdaLR(optimizer, fn)
    if name == "cosine":
        return CosineAnnealingLR(optimizer, T_max=t_max)
    raise ValueError(f"Unsupported lr scheduler {name}")


def load_split(split_path: Path) -> set:
    with split_path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    return set(data.get("val", []))


def split_bundles(bundles: List[FrameBundle], val_set: set) -> Tuple[List[FrameBundle], List[FrameBundle]]:
    train_b, val_b = [], []
    for b in bundles:
        if f"v1/{b.scenario}" in val_set:
            val_b.append(b)
        else:
            train_b.append(b)
    return train_b, val_b


class PairDataset(Dataset):
    def __init__(
        self,
        bundles: List[FrameBundle],
        cache_dir: Path,
    ):
        self.bundles = bundles
        self.cache_dir = cache_dir

    def __len__(self) -> int:
        return len(self.bundles)

    def __getitem__(self, idx: int):
        bundle = self.bundles[idx]

        # Load cached BEV for MetaDrive
        md_cache_path = self.cache_dir / "metadrive" / bundle.scenario / f"{bundle.frame}.pt"
        if not md_cache_path.exists():
            return None

        # Load cached BEV for Bench2Drive
        b2d_cache_path = self.cache_dir / "bench2drive" / bundle.scenario / f"{bundle.frame}.pt"
        if not b2d_cache_path.exists():
            return None

        try:
            # Load and validate MetaDrive BEV
            md_loaded = torch.load(md_cache_path, map_location="cpu", weights_only=True)
            if isinstance(md_loaded, dict):
                if md_loaded.get("scenario") != bundle.scenario or md_loaded.get("frame") != bundle.frame:
                    return None
                md_bev = md_loaded["bev"]
            else:
                md_bev = md_loaded

            # Load and validate Bench2Drive BEV
            b2d_loaded = torch.load(b2d_cache_path, map_location="cpu", weights_only=True)
            if isinstance(b2d_loaded, dict):
                if b2d_loaded.get("scenario") != bundle.scenario or b2d_loaded.get("frame") != bundle.frame:
                    return None
                b2d_bev = b2d_loaded["bev"]
            else:
                b2d_bev = b2d_loaded

            # Reshape precomputed cache tensors to expected format
            # Precomputed cache can have shapes like (H*W, 1, C) or (1, C, H, W)
            # Ensure they are squeezed to remove batch dimension of 1
            if md_bev.dim() == 3 and md_bev.shape[1] == 1:
                # Shape: (H*W, 1, C) -> (H*W, C)
                md_bev = md_bev.squeeze(1)
            elif md_bev.dim() == 4 and md_bev.shape[0] == 1:
                # Shape: (1, C, H, W) -> (C, H, W)
                md_bev = md_bev.squeeze(0)

            if b2d_bev.dim() == 3 and b2d_bev.shape[1] == 1:
                # Shape: (H*W, 1, C) -> (H*W, C)
                b2d_bev = b2d_bev.squeeze(1)
            elif b2d_bev.dim() == 4 and b2d_bev.shape[0] == 1:
                # Shape: (1, C, H, W) -> (C, H, W)
                b2d_bev = b2d_bev.squeeze(0)

            return bundle, md_bev, b2d_bev

        except Exception:
            return None


def collate_fn(batch: List):
    batch = [b for b in batch if b is not None]
    if not batch:
        return None
    bundles, md_bevs, b2d_bevs = zip(*batch)
    # Stack BEV tensors into batches
    md_bev_batch = torch.stack(md_bevs, dim=0)  # (B, ...)
    b2d_bev_batch = torch.stack(b2d_bevs, dim=0)  # (B, ...)
    return list(bundles), md_bev_batch, b2d_bev_batch


class FlowMatchingLit(pl.LightningModule):
    def __init__(
        self,
        lr: float = 1e-4,
        optimizer_name: str = "adamw",
        weight_decay: float = 0.01,
        lr_scheduler_name: str = "customized",
        warmup_steps: int = 500,
        lr_t_max: int = 1000,
        ema_decay: float = 0.9999,
        visualize: bool = False,
        viz_dir: Optional[Path] = None,
        viz_score_thresh: float = 0.2,
        config_path: Optional[Path] = None,
        checkpoint_path: Optional[Path] = None,
        dit_variant: str = "DiT-B/2",
    ) -> None:
        super().__init__()
        self.save_hyperparameters()
        self.lr = lr
        self.optimizer_name = optimizer_name
        self.weight_decay = weight_decay
        self.lr_scheduler_name = lr_scheduler_name
        self.warmup_steps = warmup_steps
        self.lr_t_max = lr_t_max
        self.ema_decay = ema_decay
        self.visualize_flag = visualize
        self.viz_dir = viz_dir or Path("bev_viz_pl")
        self.viz_score_thresh = viz_score_thresh
        self.config_path = config_path
        self.checkpoint_path = checkpoint_path

        # Flow model (DiT-backed)
        self.flow_model = FlowMatchingModel(dit_variant=dit_variant)
        self.ema_flow_model = deepcopy(self.flow_model)
        for p in self.ema_flow_model.parameters():
            p.requires_grad_(False)

        # UniAD model for visualization only (loaded lazily if needed)
        self.uni_model = None

    def setup(self, stage: Optional[str] = None) -> None:
        # Only load UniAD if visualization is enabled
        if self.visualize_flag and self.uni_model is None and self.config_path and self.checkpoint_path:
            uni_model, _ = load_model_and_pipeline(str(self.config_path), str(self.checkpoint_path))
            for p in uni_model.parameters():
                p.requires_grad_(False)
            uni_model.eval()
            self.uni_model = uni_model.to(self.device)

    def on_validation_epoch_end(self):
        # Force cleanup after validation
        gc.collect()
        torch.cuda.empty_cache()

    def configure_optimizers(self):
        optimizer = build_optimizer(
            self.flow_model.parameters(),
            name=self.optimizer_name,
            lr=self.lr,
            weight_decay=self.weight_decay,
        )
        scheduler = build_lr_scheduler(
            optimizer,
            name=self.lr_scheduler_name,
            warmup_steps=self.warmup_steps,
            t_max=self.lr_t_max,
        )
        if scheduler is None:
            return optimizer
        return {
            "optimizer": optimizer,
            "lr_scheduler": {
                "scheduler": scheduler,
                "interval": "step",
            },
        }

    @torch.no_grad()
    def _ema_update(self):
        if self.ema_flow_model is None:
            return
        ema_params = dict(self.ema_flow_model.named_parameters())
        for name, param in self.flow_model.named_parameters():
            ema_param = ema_params[name]
            ema_param.data.mul_(self.ema_decay).add_((1 - self.ema_decay) * param.data)

    def _flow_step(self, bundles, md_bev: torch.Tensor, b2d_bev: torch.Tensor, stage: str):
        """
        Shared flow-matching computation for train/val/test.
        """
        src_bchw = self.flow_model.reshape_bev(md_bev)
        tgt_bchw = self.flow_model.reshape_bev(b2d_bev)
        t = torch.rand(src_bchw.shape[0], device=self.device)

        x_t = self.flow_model.psi(t, noise=src_bchw, x1=tgt_bchw)
        target_velocity = self.flow_model.dt_psi(t, noise=src_bchw, x1=tgt_bchw)

        v_pred = self.flow_model(x_t, t)
        loss = (v_pred - target_velocity).pow(2).flatten(1).mean()

        log_name = f"{stage}/loss"
        self.log(
            log_name,
            loss,
            prog_bar=True,
            on_step=(stage == "train"),
            on_epoch=True,
            sync_dist=True,
        )
        return loss

    def optimizer_step(self, *args, **kwargs):
        super().optimizer_step(*args, **kwargs)
        self._ema_update()

    def _run_stage(self, batch, stage: str):
        if batch is None:
            return torch.zeros((), device=self.device)
        bundles, md_bev, b2d_bev = batch
        md_bev = md_bev.to(self.device)
        b2d_bev = b2d_bev.to(self.device)

        # if self.visualize_flag and self.global_rank == 0:
        #     if self.uni_model is not None:
        #         self.uni_model.eval()
        #     batch_size = len(bundles)
        #     for idx in range(batch_size):
        #         md_slice = md_bev[idx : idx + 1]
        #         b2d_slice = b2d_bev[idx : idx + 1]
        #         bundle = bundles[idx]
        #         out_dir = self.viz_dir / bundle.scenario
        #         out_dir.mkdir(parents=True, exist_ok=True)
        #         try:
        #             det_out, seg_out, occ_out = run_heads_from_bev(md_slice, self.uni_model, score_thresh=0.2)
        #         except Exception as e:
        #             print(f"[viz] Failed to run heads for bench2drive {bundle.scenario}/{bundle.frame}: {e}")
        #             det_out, seg_out, occ_out = None, None, None

        #         visualize_bev(
        #             md_slice,
        #             self.uni_model,
        #             score_thresh=self.viz_score_thresh,
        #             output_png=out_dir / f"{bundle.frame}_md.png",
        #             seg_data = seg_out,
        #             occ_data = occ_out,
        #         )

        #         try:
        #             det_out, seg_out, occ_out = run_heads_from_bev(b2d_slice, self.uni_model, score_thresh=0.2)
        #         except Exception as e:
        #             print(f"[viz] Failed to run heads for bench2drive {bundle.scenario}/{bundle.frame}: {e}")
        #             det_out, seg_out, occ_out = None, None, None
        #         visualize_bev(
        #             b2d_slice,
        #             self.uni_model,
        #             score_thresh=self.viz_score_thresh,
        #             output_png=out_dir / f"{bundle.frame}_b2d.png",
        #             seg_data = seg_out,
        #             occ_data = occ_out,
        #         )

        return self._flow_step(bundles, md_bev, b2d_bev, stage=stage)

    def training_step(self, batch, batch_idx: int):
        return self._run_stage(batch, stage="train")

    def validation_step(self, batch, batch_idx: int):
        return self._run_stage(batch, stage="val")

    def test_step(self, batch, batch_idx: int):
        if batch is None:
            return
        bundles, md_bev, b2d_bev = batch
        md_bev = md_bev.to(self.device)
        b2d_bev = b2d_bev.to(self.device)

        # Run flow-matching sampling from MetaDrive BEV to Bench2Drive BEV.
        sampler_model = self.ema_flow_model if self.ema_flow_model is not None else self.flow_model
        gen_bev = sampler_model.sample(md_bev)  # TODO: replace with real sampler when implemented.

        gen_bchw = self.flow_model.reshape_bev(gen_bev)
        tgt_bchw = self.flow_model.reshape_bev(b2d_bev)
        loss = (gen_bchw - tgt_bchw).pow(2).flatten(1).mean()
        self.log("test/loss", loss.detach(), prog_bar=True, on_step=False, on_epoch=True, sync_dist=True)

        if self.visualize_flag and self.global_rank == 0:
            if self.uni_model is not None:
                self.uni_model.eval()
            batch_size = len(bundles)
            for idx in range(batch_size):
                md_slice = md_bev[idx : idx + 1]
                gen_slice = gen_bev[idx : idx + 1]
                b2d_slice = b2d_bev[idx : idx + 1]
                bundle = bundles[idx]
                out_dir = self.viz_dir / bundle.scenario
                out_dir.mkdir(parents=True, exist_ok=True)

                visualize_bev(
                    md_slice,
                    self.uni_model,
                    score_thresh=self.viz_score_thresh,
                    output_png=out_dir / f"{bundle.frame}_md.png",
                )
                visualize_bev(
                    gen_slice,
                    self.uni_model,
                    score_thresh=self.viz_score_thresh,
                    output_png=out_dir / f"{bundle.frame}_gen.png",
                )
                visualize_bev(
                    b2d_slice,
                    self.uni_model,
                    score_thresh=self.viz_score_thresh,
                    output_png=out_dir / f"{bundle.frame}_b2d.png",
                )


class PairDataModule(pl.LightningDataModule):
    def __init__(
        self,
        pairs_path: Path,
        split_path: Path,
        cache_dir: Path,
        batch_size: int = 1,
        num_workers: int = 4,
        max_samples: Optional[int] = None,
    ) -> None:
        super().__init__()
        self.pairs_path = pairs_path
        self.split_path = split_path
        self.cache_dir = cache_dir
        self.batch_size = batch_size
        self.num_workers = num_workers
        self.train_bundles: List[FrameBundle] = []
        self.val_bundles: List[FrameBundle] = []
        self.max_samples = max_samples

    def setup(self, stage: Optional[str] = None) -> None:
        bundles = load_frame_bundles(self.pairs_path)
        val_set = load_split(self.split_path)
        self.train_bundles, self.val_bundles = split_bundles(bundles, val_set)
        if self.max_samples is not None:
            self.train_bundles = self.train_bundles[:self.max_samples]

    def train_dataloader(self):
        return DataLoader(
            PairDataset(
                self.train_bundles,
                cache_dir=self.cache_dir,
            ),
            batch_size=self.batch_size,
            shuffle=True,
            num_workers=self.num_workers,
            collate_fn=collate_fn,
            pin_memory=True,
            persistent_workers=(self.num_workers > 0),
        )

    def val_dataloader(self):
        return DataLoader(
            PairDataset(
                self.val_bundles,
                cache_dir=self.cache_dir,
            ),
            batch_size=self.batch_size,
            shuffle=False,
            num_workers=self.num_workers,
            collate_fn=collate_fn,
            pin_memory=True,
            persistent_workers=(self.num_workers > 0),
        )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Lightning training for UniAD BEV flow matching.")
    parser.add_argument("--pairs", type=Path, required=True, help="Frame pairs JSONL.")
    parser.add_argument("--split", type=Path, required=True, help="JSON split with key 'val'.")
    parser.add_argument("--cache-dir", type=Path, required=True, help="Directory with precomputed BEV cache.")
    parser.add_argument("--config", type=Path, required=True, help="UniAD config path (for test visualization).")
    parser.add_argument("--checkpoint", type=Path, required=True, help="UniAD checkpoint path (for test visualization).")
    parser.add_argument("--batch-size", type=int, default=1)
    parser.add_argument("--num-workers", type=int, default=4)
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--optimizer", type=str, default="adamw", choices=["adam", "adamw"], help="Optimizer type.")
    parser.add_argument("--weight-decay", type=float, default=0.01)
    parser.add_argument("--lr-scheduler", type=str, default="customized", choices=["none", "customized", "cosine"])
    parser.add_argument("--warmup-steps", type=int, default=500, help="Warmup steps for customized scheduler.")
    parser.add_argument("--lr-t-max", type=int, default=1000, help="T_max for cosine scheduler.")
    parser.add_argument("--ema-decay", type=float, default=0.9999)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--accelerator", type=str, default="gpu" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--devices", default="auto", help="Lightning devices arg (e.g., 1, 2, 'auto').")
    parser.add_argument("--strategy", type=str, default="ddp", help="Lightning strategy (e.g., ddp, auto).")
    parser.add_argument("--visualize", action="store_true", help="Enable test visualizations.")
    parser.add_argument("--viz-dir", type=Path, default=Path("bev_viz_pl"), help="Directory for visualizations.")
    parser.add_argument("--viz-score-thresh", type=float, default=0.2)
    parser.add_argument("--ckpt-dir", type=Path, required=True, help="Directory to save checkpoints.")
    parser.add_argument("--resume-from", type=Path, default=None, help="Resume from checkpoint path.")
    parser.add_argument("--wandb", action="store_true", help="Enable Weights & Biases logging.")
    parser.add_argument("--wandb-project", type=str, default="BevFlow", help="W&B project name.")
    parser.add_argument("--wandb-run-name", type=str, default=None, help="W&B run name (wandb name arg).")
    parser.add_argument("--dit-variant", type=str, default="DiT-B/2", help="DiT architecture choices.")
    parser.add_argument("--max-samples", type=int, default=None, help="Optional cap on number of training samples.")
    parser.add_argument("--save-every-n-epochs", type=int, default=1, help="Save checkpoint every N epochs.")
    return parser.parse_args()


def main():
    args = parse_args()
    set_seed(args.seed)
    pl.seed_everything(args.seed, workers=True)

    torch.set_float32_matmul_precision("high")

    datamodule = PairDataModule(
        pairs_path=args.pairs,
        split_path=args.split,
        cache_dir=args.cache_dir,
        batch_size=args.batch_size,
        num_workers=args.num_workers,
        max_samples=args.max_samples,
    )

    lit_model = FlowMatchingLit(
        lr=args.lr,
        optimizer_name=args.optimizer,
        weight_decay=args.weight_decay,
        lr_scheduler_name=args.lr_scheduler,
        warmup_steps=args.warmup_steps,
        lr_t_max=args.lr_t_max,
        ema_decay=args.ema_decay,
        visualize=args.visualize,
        viz_dir=args.viz_dir,
        viz_score_thresh=args.viz_score_thresh,
        config_path=args.config,
        checkpoint_path=args.checkpoint,
        dit_variant = args.dit_variant,
    )

    ckpt_dir = args.ckpt_dir
    ckpt_dir.mkdir(parents=True, exist_ok=True)

    # Build a default run name if not provided: include DiT variant.
    if args.wandb_run_name is None:
        dit_variant = getattr(lit_model.flow_model, "dit_variant", "unknown_dit")
        args.wandb_run_name = f"bevflow-{dit_variant}"

    checkpoint_cb = ModelCheckpoint(
        dirpath=str(ckpt_dir),
        # {epoch} and {step} already render as "epoch=..." / "step=...", so avoid duplicating prefixes.
        filename="{epoch}-{step}",
        save_top_k=-1,
        every_n_epochs=args.save_every_n_epochs,
        save_weights_only=False,
    )

    logger = None
    if args.wandb:
        wandb.login(key="caad08df59bfd0cb22f3613849ad66faeb65d4b0")
        logger = WandbLogger(
            project=args.wandb_project,
            name=args.wandb_run_name,
            save_dir=str(ckpt_dir),
            config=vars(args),
        )

    trainer = pl.Trainer(
        max_epochs=args.epochs,
        accelerator=args.accelerator,
        devices=args.devices,
        strategy=args.strategy,
        precision=32,  # high precision
        logger=logger,
        enable_checkpointing=True,
        callbacks=[checkpoint_cb],
        log_every_n_steps=10,
        enable_progress_bar=True,
    )

    trainer.fit(lit_model, datamodule=datamodule, ckpt_path=str(args.resume_from) if args.resume_from else None)


if __name__ == "__main__":
    main()
